<?php

/**
 * @file
 * Contains hs_events_decoupled_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hs_events_decoupled_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hs_events_decoupled_blocks module.
    case 'help.page.hs_events_decoupled_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Decoupled blocks for display') . '</p>';
      return $output;

    default:
  }

//  \Drupal\pdb_react\Plugin\Block\ReactBlock::attachSettings()
}
